import {
  db,
  animalsTable,
  productsTable,
  vetsTable,
  hospitalsTable,
  volunteersTable,
  reportsTable,
  casesTable,
} from "@workspace/db";

async function seed() {
  console.log("Seeding database...");

  // Seed hospitals
  const hospitals = await db.insert(hospitalsTable).values([
    {
      name: "Government Veterinary Hospital, Mumbai",
      address: "123, Andheri West, Mumbai",
      district: "Mumbai",
      state: "Maharashtra",
      phone: "022-26200100",
      email: "gvh.mumbai@gov.in",
      latitude: 19.119,
      longitude: 72.846,
      totalBeds: 50,
      availableBeds: 12,
      isGovernment: true,
    },
    {
      name: "District Animal Hospital, Delhi",
      address: "45, Connaught Place, New Delhi",
      district: "New Delhi",
      state: "Delhi",
      phone: "011-23456789",
      email: "dah.delhi@gov.in",
      latitude: 28.634,
      longitude: 77.219,
      totalBeds: 80,
      availableBeds: 25,
      isGovernment: true,
    },
    {
      name: "Government Veterinary College & Hospital, Bengaluru",
      address: "Bellary Road, Hebbal, Bengaluru",
      district: "Bengaluru",
      state: "Karnataka",
      phone: "080-23415195",
      email: "gvch.blr@gov.in",
      latitude: 13.035,
      longitude: 77.590,
      totalBeds: 120,
      availableBeds: 40,
      isGovernment: true,
    },
    {
      name: "Madras Veterinary College Hospital",
      address: "Vepery, Chennai",
      district: "Chennai",
      state: "Tamil Nadu",
      phone: "044-25361429",
      email: "mvc.chennai@gov.in",
      latitude: 13.083,
      longitude: 80.271,
      totalBeds: 100,
      availableBeds: 30,
      isGovernment: true,
    },
    {
      name: "Government Animal Hospital, Hyderabad",
      address: "Nampally, Hyderabad",
      district: "Hyderabad",
      state: "Telangana",
      phone: "040-24600123",
      email: "gah.hyd@gov.in",
      latitude: 17.392,
      longitude: 78.474,
      totalBeds: 60,
      availableBeds: 15,
      isGovernment: true,
    },
  ]).returning();

  console.log(`Seeded ${hospitals.length} hospitals`);

  // Seed vets
  const vets = await db.insert(vetsTable).values([
    {
      name: "Dr. Priya Sharma",
      email: "priya.sharma@gov.in",
      phone: "9876543210",
      specialization: "Small Animals & Surgery",
      registrationNumber: "MH-VET-2341",
      hospitalId: hospitals[0].id,
      district: "Mumbai",
      state: "Maharashtra",
      isAvailable: true,
    },
    {
      name: "Dr. Rahul Mehta",
      email: "rahul.mehta@gov.in",
      phone: "9876543211",
      specialization: "Wildlife Medicine",
      registrationNumber: "DL-VET-1892",
      hospitalId: hospitals[1].id,
      district: "New Delhi",
      state: "Delhi",
      isAvailable: true,
    },
    {
      name: "Dr. Sunita Krishnan",
      email: "sunita.k@gov.in",
      phone: "9876543212",
      specialization: "Large Animals & Bovine",
      registrationNumber: "KA-VET-3012",
      hospitalId: hospitals[2].id,
      district: "Bengaluru",
      state: "Karnataka",
      isAvailable: false,
    },
    {
      name: "Dr. Arun Nair",
      email: "arun.nair@gov.in",
      phone: "9876543213",
      specialization: "Avian & Exotic Animals",
      registrationNumber: "TN-VET-0892",
      hospitalId: hospitals[3].id,
      district: "Chennai",
      state: "Tamil Nadu",
      isAvailable: true,
    },
    {
      name: "Dr. Lakshmi Reddy",
      email: "lakshmi.r@gov.in",
      phone: "9876543214",
      specialization: "Emergency & Critical Care",
      registrationNumber: "TS-VET-2201",
      hospitalId: hospitals[4].id,
      district: "Hyderabad",
      state: "Telangana",
      isAvailable: true,
    },
  ]).returning();

  console.log(`Seeded ${vets.length} vets`);

  // Seed animals for adoption
  const animals = await db.insert(animalsTable).values([
    {
      name: "Bruno",
      species: "Dog",
      breed: "Labrador Mix",
      age: "2 years",
      gender: "Male",
      color: "Golden",
      weight: "22 kg",
      vaccinationStatus: "Fully Vaccinated",
      medicalHistory: "Recovered from road accident, now fully healthy",
      temperament: "Friendly, Playful, Good with children",
      rescueStory: "Bruno was found injured near the highway in Mumbai. After 3 months of treatment at the government vet hospital, he recovered fully and is now looking for a loving home.",
      shelterName: "Mumbai Animal Welfare Shelter",
      shelterDistrict: "Mumbai",
      shelterState: "Maharashtra",
      photoUrl: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=400&h=300&fit=crop",
      status: "available",
    },
    {
      name: "Mia",
      species: "Cat",
      breed: "Indian Domestic",
      age: "1 year",
      gender: "Female",
      color: "Orange & White",
      weight: "3.5 kg",
      vaccinationStatus: "Fully Vaccinated",
      medicalHistory: "Treated for malnutrition, now healthy",
      temperament: "Calm, Affectionate, Independent",
      rescueStory: "Mia was rescued as a kitten from a flood-affected area in Chennai. She loves sitting by the window and is very affectionate.",
      shelterName: "Chennai Animal Care Center",
      shelterDistrict: "Chennai",
      shelterState: "Tamil Nadu",
      photoUrl: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400&h=300&fit=crop",
      status: "available",
    },
    {
      name: "Kali",
      species: "Dog",
      breed: "Indian Pariah",
      age: "3 years",
      gender: "Female",
      color: "Black & Brown",
      weight: "18 kg",
      vaccinationStatus: "Fully Vaccinated",
      medicalHistory: "Treated for skin infection, fully recovered",
      temperament: "Alert, Loyal, Good guard dog",
      rescueStory: "Kali was rescued from a construction site in Delhi where she was being harassed. She is very loyal once she trusts you.",
      shelterName: "Delhi Pet Welfare Society",
      shelterDistrict: "New Delhi",
      shelterState: "Delhi",
      photoUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=300&fit=crop",
      status: "available",
    },
    {
      name: "Whiskers",
      species: "Cat",
      breed: "Persian Mix",
      age: "4 years",
      gender: "Male",
      color: "White & Grey",
      weight: "4.2 kg",
      vaccinationStatus: "Partially Vaccinated",
      medicalHistory: "Eye surgery performed, vision restored",
      temperament: "Gentle, Calm, Good with other cats",
      rescueStory: "Whiskers was found with an eye injury in Bengaluru. After successful surgery, he loves cuddling and sleeping in warm spots.",
      shelterName: "Bengaluru Animal Rescue Trust",
      shelterDistrict: "Bengaluru",
      shelterState: "Karnataka",
      photoUrl: "https://images.unsplash.com/photo-1518791841217-8f162f1912da?w=400&h=300&fit=crop",
      status: "available",
    },
    {
      name: "Raja",
      species: "Dog",
      breed: "German Shepherd Mix",
      age: "5 years",
      gender: "Male",
      color: "Black & Tan",
      weight: "30 kg",
      vaccinationStatus: "Fully Vaccinated",
      medicalHistory: "Treated for heartworm, now fully recovered",
      temperament: "Intelligent, Energetic, Needs experienced owner",
      rescueStory: "Raja was abandoned by his previous owner. Despite his rough past, he is extremely intelligent and responds well to training.",
      shelterName: "Hyderabad Animal Welfare Center",
      shelterDistrict: "Hyderabad",
      shelterState: "Telangana",
      photoUrl: "https://images.unsplash.com/photo-1568572933382-74d440ac3d41?w=400&h=300&fit=crop",
      status: "available",
    },
    {
      name: "Golu",
      species: "Dog",
      breed: "Pomeranian Mix",
      age: "1 year",
      gender: "Male",
      color: "White",
      weight: "5 kg",
      vaccinationStatus: "Fully Vaccinated",
      medicalHistory: "Healthy, no prior medical issues",
      temperament: "Playful, Energetic, Loves cuddles",
      rescueStory: "Golu was rescued from an illegal puppy mill in Pune. He is completely healthy and ready for his forever home.",
      shelterName: "Pune Animal Aid",
      shelterDistrict: "Pune",
      shelterState: "Maharashtra",
      photoUrl: "https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?w=400&h=300&fit=crop",
      status: "available",
    },
  ]).returning();

  console.log(`Seeded ${animals.length} animals`);

  // Seed products
  const products = await db.insert(productsTable).values([
    {
      name: "Royal Canin Adult Dog Food",
      description: "Complete dry food for adult dogs. Maintains healthy weight and supports joint health. Available in 3kg, 7kg, and 15kg packs.",
      category: "Pet Food",
      price: 1899,
      originalPrice: 2299,
      brand: "Royal Canin",
      imageUrl: "https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?w=400&h=300&fit=crop",
      rating: 4.7,
      reviewCount: 2340,
      inStock: true,
      isFeatured: true,
    },
    {
      name: "Interactive Puzzle Toy for Dogs",
      description: "Keep your dog mentally stimulated with this interactive puzzle feeder. 3 difficulty levels, dishwasher safe.",
      category: "Pet Toys",
      price: 649,
      originalPrice: 899,
      brand: "Kong",
      imageUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=300&fit=crop",
      rating: 4.5,
      reviewCount: 892,
      inStock: true,
      isFeatured: true,
    },
    {
      name: "Cat Grooming Kit - 5 in 1",
      description: "Complete grooming set with slicker brush, deshedding tool, nail clippers, ear cleaning solution, and toothbrush kit.",
      category: "Grooming Products",
      price: 899,
      originalPrice: null,
      brand: "Furminator",
      imageUrl: "https://images.unsplash.com/photo-1582797493098-a4afe081dd45?w=400&h=300&fit=crop",
      rating: 4.3,
      reviewCount: 456,
      inStock: true,
      isFeatured: false,
    },
    {
      name: "Tick & Flea Prevention Collar",
      description: "8-month protection against ticks, fleas, and mosquitoes. Water-resistant and suitable for dogs over 8 weeks.",
      category: "Medicines",
      price: 1299,
      originalPrice: 1599,
      brand: "Seresto",
      imageUrl: "https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?w=400&h=300&fit=crop",
      rating: 4.6,
      reviewCount: 1234,
      inStock: true,
      isFeatured: true,
    },
    {
      name: "Orthopedic Pet Bed - Large",
      description: "Memory foam orthopedic bed for dogs and cats. Water-resistant cover, easy to clean. Suitable for dogs up to 40kg.",
      category: "Beds & Carriers",
      price: 2499,
      originalPrice: 3499,
      brand: "PetSafe",
      imageUrl: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=300&fit=crop",
      rating: 4.8,
      reviewCount: 678,
      inStock: true,
      isFeatured: true,
    },
    {
      name: "Adjustable Dog Harness",
      description: "Comfortable, no-pull harness with reflective strips for night walks. Easy to put on and take off. Available in S, M, L, XL.",
      category: "Pet Accessories",
      price: 799,
      originalPrice: 1099,
      brand: "Ruffwear",
      imageUrl: "https://images.unsplash.com/photo-1535930891776-0c2dfb7fda1a?w=400&h=300&fit=crop",
      rating: 4.4,
      reviewCount: 987,
      inStock: true,
      isFeatured: false,
    },
    {
      name: "Whiskas Adult Cat Food",
      description: "Nutritionally complete wet food for adult cats. Real chicken in jelly. Pack of 12 pouches x 85g.",
      category: "Pet Food",
      price: 549,
      originalPrice: null,
      brand: "Whiskas",
      imageUrl: "https://images.unsplash.com/photo-1517849845537-4d257902454a?w=400&h=300&fit=crop",
      rating: 4.2,
      reviewCount: 1567,
      inStock: true,
      isFeatured: false,
    },
    {
      name: "Feather Wand Cat Toy",
      description: "Interactive teaser wand with bell and feather. Telescoping rod extends to 90cm. Replacement feathers included.",
      category: "Pet Toys",
      price: 299,
      originalPrice: 399,
      brand: "SmartyKat",
      imageUrl: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400&h=300&fit=crop",
      rating: 4.6,
      reviewCount: 2345,
      inStock: true,
      isFeatured: false,
    },
    {
      name: "Pet First Aid Kit",
      description: "Complete first aid kit for pets. Includes bandages, antiseptic wipes, scissors, tweezers, and emergency guide.",
      category: "Medicines",
      price: 1199,
      originalPrice: null,
      brand: "Adventure Medical",
      imageUrl: "https://images.unsplash.com/photo-1583512603806-077998240c7a?w=400&h=300&fit=crop",
      rating: 4.7,
      reviewCount: 345,
      inStock: true,
      isFeatured: false,
    },
    {
      name: "Airline Approved Pet Carrier",
      description: "IATA compliant pet carrier for air travel. Ventilated sides, secure latches. Suitable for cats and small dogs up to 10kg.",
      category: "Beds & Carriers",
      price: 3499,
      originalPrice: 4500,
      brand: "Petmate",
      imageUrl: "https://images.unsplash.com/photo-1542736667-069246bdbc6d?w=400&h=300&fit=crop",
      rating: 4.5,
      reviewCount: 234,
      inStock: true,
      isFeatured: false,
    },
    {
      name: "Dog Dental Chews",
      description: "Enzymatic dental chews for dogs. Reduces tartar and plaque buildup. Natural ingredients, no artificial flavors.",
      category: "Pet Food",
      price: 449,
      originalPrice: 599,
      brand: "Virbac",
      imageUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&h=300&fit=crop",
      rating: 4.3,
      reviewCount: 789,
      inStock: true,
      isFeatured: false,
    },
    {
      name: "Stainless Steel Pet Bowl Set",
      description: "Set of 2 heavy-duty stainless steel bowls. Non-slip base, dishwasher safe. Available in 3 sizes.",
      category: "Pet Accessories",
      price: 499,
      originalPrice: null,
      brand: "Petmate",
      imageUrl: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=300&fit=crop",
      rating: 4.6,
      reviewCount: 1890,
      inStock: true,
      isFeatured: false,
    },
  ]).returning();

  console.log(`Seeded ${products.length} products`);

  // Seed volunteers
  const volunteers = await db.insert(volunteersTable).values([
    {
      name: "Anita Patel",
      email: "anita.patel@gmail.com",
      phone: "9812345678",
      type: "Individual",
      district: "Mumbai",
      state: "Maharashtra",
      skills: "Transport, First Aid, Foster Care",
      availability: "Weekends",
      vehicleAvailable: true,
      status: "active",
    },
    {
      name: "People for Animals Delhi",
      email: "contact@pfadelhi.org",
      phone: "9823456789",
      type: "NGO",
      organizationName: "People for Animals Delhi",
      district: "New Delhi",
      state: "Delhi",
      skills: "Rescue Operations, Veterinary Assistance, Fundraising",
      availability: "24/7",
      vehicleAvailable: true,
      status: "active",
    },
    {
      name: "Kiran Rao",
      email: "kiran.rao@gmail.com",
      phone: "9834567890",
      type: "Individual",
      district: "Bengaluru",
      state: "Karnataka",
      skills: "Veterinary Assistance, First Aid",
      availability: "Evenings and Weekends",
      vehicleAvailable: false,
      status: "active",
    },
  ]).returning();

  console.log(`Seeded ${volunteers.length} volunteers`);

  // Seed some sample reports/cases
  const report1 = await db.insert(reportsTable).values({
    caseId: "ARI-SAMPLE-001",
    reporterName: "Rajesh Kumar",
    reporterPhone: "9876000001",
    reporterEmail: "rajesh@example.com",
    animalType: "Dog",
    description: "Stray dog with a broken leg, unable to walk, lying near traffic signal",
    severity: "severe",
    latitude: 19.076,
    longitude: 72.877,
    locationAddress: "Near Andheri Station, Mumbai",
    district: "Mumbai",
    state: "Maharashtra",
    status: "in_treatment",
    assignedVetId: vets[0].id,
    assignedHospitalId: hospitals[0].id,
    treatmentNotes: "Dog admitted, surgery performed on fractured left foreleg. Recovery underway.",
  }).returning();

  await db.insert(casesTable).values({
    caseId: "ARI-SAMPLE-001",
    animalType: "Dog",
    description: "Stray dog with a broken leg, unable to walk, lying near traffic signal",
    severity: "severe",
    status: "in_treatment",
    district: "Mumbai",
    state: "Maharashtra",
    latitude: 19.076,
    longitude: 72.877,
    locationAddress: "Near Andheri Station, Mumbai",
    rescueTime: "2 hours after report",
    firstAid: "Leg immobilized, pain medication administered",
    vetName: vets[0].name,
    vetPhone: vets[0].phone,
    hospitalName: hospitals[0].name,
    treatmentUpdates: "Day 1: Surgery successful. Day 3: Post-op recovery progressing well. Day 7: Beginning physiotherapy.",
    recoveryProgress: "Good - Expected recovery in 3-4 weeks",
    reportId: report1[0].id,
  });

  const report2 = await db.insert(reportsTable).values({
    caseId: "ARI-SAMPLE-002",
    reporterName: "Meena Singh",
    reporterPhone: "9876000002",
    reporterEmail: "meena@example.com",
    animalType: "Cow",
    description: "Cow with a large wound on its leg, bleeding severely",
    severity: "critical",
    latitude: 28.635,
    longitude: 77.221,
    locationAddress: "Connaught Place, New Delhi",
    district: "New Delhi",
    state: "Delhi",
    status: "recovered",
    assignedVetId: vets[1].id,
    assignedHospitalId: hospitals[1].id,
    treatmentNotes: "Wound cleaned and stitched. Animal under observation.",
    medicalReport: "Deep laceration on right hind leg. Treated with wound irrigation, suturing, and antibiotics. Full recovery achieved.",
  }).returning();

  await db.insert(casesTable).values({
    caseId: "ARI-SAMPLE-002",
    animalType: "Cow",
    description: "Cow with a large wound on its leg, bleeding severely",
    severity: "critical",
    status: "recovered",
    district: "New Delhi",
    state: "Delhi",
    latitude: 28.635,
    longitude: 77.221,
    locationAddress: "Connaught Place, New Delhi",
    rescueTime: "45 minutes after report",
    firstAid: "Bleeding controlled with pressure bandage",
    vetName: vets[1].name,
    vetPhone: vets[1].phone,
    hospitalName: hospitals[1].name,
    treatmentUpdates: "Wound sutured. Antibiotics course started. Day 14: Full recovery confirmed.",
    recoveryProgress: "Fully recovered",
    medicalReport: "Deep laceration successfully treated. Animal discharged in good health.",
    releaseDetails: "Animal returned to owner on Day 14 of treatment. Follow-up visit scheduled.",
    reportId: report2[0].id,
  });

  console.log("Seeded sample reports and cases");
  console.log("Database seeding complete!");
}

seed().catch(console.error);
